# Generated by Django 5.0.3 on 2025-11-26 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('estimated_hours', models.IntegerField()),
                ('importance', models.IntegerField()),
                ('priorityScore', models.FloatField(default=0.0)),
                ('smartPriorityScore', models.FloatField(default=0.0)),
                ('completed', models.BooleanField(default=False)),
                ('circularTask', models.BooleanField(default=False)),
                ('dependencies', models.ManyToManyField(blank=True, related_name='required_by', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'number')},
            },
        ),
    ]
